language: python
sudo: false

env:
   - LUA="lua=5.1"
   - LUA="lua=5.2"
   - LUA="lua=5.3"
   - LUA="luajit=2.0"
   - LUA="luajit=2.1"

before_install:
   # Uses sed to replace the SSH URL for submodules with the public URL
   - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
   - git submodule update --init --recursive
   - pip install hererocks
   - hererocks lua_install -r^ --$LUA
   - export PATH=$PATH:$PWD/lua_install/bin

install:

git:
   submodules: false

notifications:
   email: false
